apiVersion: v1
kind: Secret
metadata:
  name: hostwebapi-secret
type: Opaque
data:
  # mongodb://user:password@mongodb-service:27017
  ConnectionStrings__CleanArchitectureSkeletonMongoDb: bW9uZ29kYjovL3VzZXI6cGFzc3dvcmRAbW9uZ29kYi1zZXJ2aWNlOjI3MDE3
  # http://otel-service:4317
  ConnectionStrings__OpenTelemetry: aHR0cDovL290ZWwtc2VydmljZTo0MzE3
  # user
  MONGO_INITDB_ROOT_USERNAME: dXNlcg==
  # password
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ=
  # CleanArchitecture
  MONGO_INITDB_DATABASE: Q2xlYW5BcmNoaXRlY3R1cmU=
