apiVersion: v1
kind: Service
metadata:
  name: otel-service
spec:
  selector:
    app: otel
  ports:
    - name: prometheus-exposed-metrics
      protocol: TCP
      port: 8888
      targetPort: 8888
    - name: prometheus-exported-metrics
      protocol: TCP
      port: 8889
      targetPort: 8889
    - name: otlp-grpc
      protocol: TCP
      port: 4317
      targetPort: 4317
    - name: otlp-http
      protocol: TCP
      port: 4318
      targetPort: 4318
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-configmap
data:
  otel-collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    
    processors:
      batch:
    
    exporters:
      logging:
        verbosity: detailed

      otlphttp:
        endpoint: https://otlp-gateway-prod-us-east-0.grafana.net/otlp
        headers:
          Authorization: Basic MTAwOTY1MTpnbGNfZXlKdklqb2lPVEF4TURJMElpd2liaUk2SW5OMFlXTnJMVEV3TURrMk5URXRiM1JzY0MxM2NtbDBaUzF3Y25WbFltRnZkR3h3SWl3aWF5STZJblE1ZDNadGN6Z3hTM2xWWmpKRk4yOUtPR3MxTmxjMk5TSXNJbTBpT25zaWNpSTZJbkJ5YjJRdGRYTXRaV0Z6ZEMwd0luMTk=
    
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp]
        logs:
          receivers: [otlp]
          processors: []
          exporters: [otlphttp, logging]
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetry-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel
  template:
    metadata:
      labels:
        app: otel
    spec:
      containers:
      - name: otel
        image: otel/opentelemetry-collector-contrib:latest
        command:
          - "/otelcol-contrib"
          - "--config=/etc/otel/otel-collector.yaml"
        ports:
        - containerPort: 27017
        - containerPort: 8889
        - containerPort: 4317
        - containerPort: 4318
        resources:
          limits:
            cpu: 1000m
            memory: 600Mi
          requests:
            cpu: 50m
            memory: 32Mi
        volumeMounts:
        - name: otel-configuration
          mountPath: /etc/otel
      volumes:
      - name: otel-configuration
        configMap:
          name: otel-configmap
              
