apiVersion: v1
kind: Service
metadata:
  name: otel-service
spec:
  selector:
    app: otel
    tier: backend
  ports:
    - name: prometheus-exposed-metrics
      protocol: TCP
      port: 8888
      targetPort: 8888
    - name: prometheus-exported-metrics
      protocol: TCP
      port: 8889
      targetPort: 8889
    - name: otlp-grpc
      protocol: TCP
      port: 4317
      targetPort: 4317
---


apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-configmap
data:
  otel-collector.yaml: |
    # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    
    # Configure exporters
    #######
    # LOCAL #
    #######
    prometheus:
      endpoint: 0.0.0.0:8889
      send_timestamps: true
    loki:
      endpoint: http://loki-grafana:3100/loki/api/v1/push
      tls:
        insecure: true
    otlp/1:
      endpoint: tempo-grafana:4317
      tls:
        insecure: true
    
    ###############
    # GRAFANA CLOUD #
    ###############
    otlphttp:
      endpoint: https://otlp-gateway-prod-us-east-0.grafana.net/otlp
      headers:
        Authorization: Basic ODM5OTgxOmdsY19leUp2SWpvaU9UQXhNREkwSWl3aWJpSTZJbk4wWVdOckxUZ3pPVGs0TVMxdmRHeHdMWGR5YVhSbExXZHlZV1poYm1GdmRHVnNZV2RsYm5SMGIydGxiaUlzSW1zaU9pSmhUMDVCTWpReFQycHBlRFJQYlRoV05USXlaWFEyT0ZNaUxDSnRJanA3SW5JaU9pSndjbTlrTFhWekxXVmhjM1F0TUNKOWZRPT0=
    
    # https://opentelemetry.io/docs/collector/configuration/#processors
    processors:
      batch:
    
    # https://opentelemetry.io/docs/collector/configuration/#service
    # https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/design.md#pipelines
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/1, otlphttp]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus, otlphttp]
        logs:
          receivers: [otlp]
          processors: []
          exporters: [loki, otlphttp]
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetry-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel
  template:
    metadata:
      labels:
        app: otel
    spec:
      containers:
      - name: otel
        image: otel/opentelemetry-collector-contrib:latest
        ports:
        - containerPort: 27017
        - containerPort: 8889
        - containerPort: 4317
        resources:
          limits:
            cpu: 1000m
            memory: 600Mi
          requests:
            cpu: 50m
            memory: 32Mi
        volumeMounts:
        - name: otel-configuration
          mountPath: /etc/otel
      volumes:
      - name: otel-configuration
        configMap:
          name: otel-configmap
              
