version: '3.8'

networks:
  cleanArchitectureNetwork:
    driver: bridge

services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    networks:
      - cleanArchitectureNetwork
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME_SKELETON}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD_SKELETON}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE_SKELETON}
    volumes:
      - ./MongoDB/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_data:/data
      - mongodb_data:/data/db
      - mongodb_data:/data/configdb

volumes:
  mongodb_data:
  