version: '3.8'

networks:
  telemetryNetwork:
    driver: bridge

services:
  opentelemetry-collector:
    image: otel/opentelemetry-collector:latest
    container_name: opentelemetry_collector
    networks:
      - telemetryNetwork
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./Observability/otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "4317:4317"   # OTLP gRPC receiver
  