services:
  ## API ##
  dotnetapp:
    image: dotnetapp/cleanarchitecture:latest
    restart: always
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Path
      - ASPNETCORE_Kestrel__Certificates__Default__Password
      - ASPNETCORE_ENVIRONMENT
      - ASPNETCORE_URLS
      - AppName
      - keysFolder
      - ConnectionStrings__CleanArchitectureSkeletonMongoDb
      - ConnectionStrings__OpenTelemetry
    ports:
      - "80:80"
      - "443:443"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost/health | grep -w 'healthy' || exit 1"]
      interval: 1s
      timeout: 10s
      retries: 3
      start_period: 2s
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 256M
      restart_policy:
        condition: on-failure
    volumes:
      - dotnetapp_keys_data:/keysFolder

volumes:
  dotnetapp_keys_data:
