version: '3.8'

## Configuracion de Grafana para localhost
## En un entorno de DEV, PRE o PRO se suele acceder desde la web de grafana cloud
services:
  grafana-opentelemetry:
    image: grafana/grafana
    container_name: grafana_opentelemetry
    networks:
      - telemetryNetwork
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER_SKELETON}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD_SKELETON}
      - GF_USERS_ALLOW_SIGN_UP=${GF_USERS_ALLOW_SIGN_UP_SKELETON}
    volumes:
      - ./Observability/grafana/grafana.yaml:/etc/grafana/provisioning/datasources/all.yaml
      - grafana_metrics_data:/var/lib/grafana
    ports:
      - 3000:3000


  prometheus-opentelemetry:
    image: prom/prometheus:latest
    container_name: prometheus_opentelemetry
    networks:
      - telemetryNetwork
    volumes:
      - ./Observability/grafana/prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus_metrics_data:/prometheus
    ports:
      - 9090:9090

volumes:
  grafana_metrics_data:
  prometheus_metrics_data:
  