services:
  ## API ##
  dotnetapp:
    container_name: HostWebApi
    image: dotnetapp/cleanarchitecture:latest
    restart: always
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Path
      - ASPNETCORE_Kestrel__Certificates__Default__Password
      - ASPNETCORE_ENVIRONMENT
      - ASPNETCORE_URLS
      - AppName
      - keysFolder
      - ConnectionStrings__CleanArchitectureSkeletonMongoDb
      - ConnectionStrings__OpenTelemetry
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - dotnetapp_keys_data:/keysFolder
    depends_on:
      - mongodb
      - opentelemetry-collector

      
  ## Open Telemetry ##
  opentelemetry-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: opentelemetry_collector
    restart: always
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./Observability/otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "4317:4317" # OTLP gRPC receiver

  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
    volumes:
      - ./MongoDB/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_data:/data
      - mongodb_data:/data/db
      - mongodb_data:/data/configdb

volumes:
  dotnetapp_keys_data:
  mongodb_data:
