# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Docker_build

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Docker
      uses: docker/setup-buildx-action@v3

    - name: Ejecutar docker test
      working-directory: ./.docker
      run: |
        ls -la
        pwsh -File ./docker-compose.ps1 up test
    
    - name: Eliminar docker test
      working-directory: ./.docker
      run: |
        ls -la
        pwsh -File ./docker-compose.ps1 down test v
