# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: docker build and push

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Docker
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker
      uses: docker/login-action@v3
      with:
          username: ${{secrets.DOCKER_HUB_USER}}
          password: ${{secrets.DOCKER_HUB_TOKEN}}

    - name: Build docker
      run: |
        docker compose -f docker-compose.buildhostwebapi.yml build

    - name: Push to Docker Registry
      run: |
        docker push ${{secrets.DOCKER_HUB_USER}}/cleanarchitecture:latest
